version: "3.9"

services:
  dev:
    build:
      context: ./client-ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client-ui:/app/
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
     - ./server/src:/app/src 
     - ./server/prisma:/app/prisma 
     - ./server/package.json:/app/package.json 
     - ./server/package-lock.json:/app/package-lock.json
    ports:
      - 3000:3000 
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://root:password@db:5432/TimeTracker 
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: root  
      POSTGRES_PASSWORD: password
      POSTGRES_DB: TimeTracker
    ports:
      - '5432:5432' 
    expose:
      - '5432'  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'      